### ISSUE TITLE
douyin推流这块代码可以借鉴下吗

### ISSUE THREAD

**Issue by lichao252244354** [kloein/douyin#1]
你好，抖音直播推流地址这块是如何通过扫二维码获取的，这块代码逻辑可以介绍下吗？一直没有找到

**Comment by kloein** [comment]
你好，本项目并没有实现直播推流模块呢，详细的api可以参考[抖音项目【青训营】](https://bytedance.feishu.cn/docx/doxcnbgkMy2J0Y3E6ihqrvtHXPg)
